# Generated by Django 3.1.3 on 2020-11-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='owner_id',
            new_name='bet_owner_user_id',
        ),
        migrations.RenameField(
            model_name='userbet',
            old_name='owner_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='bet',
            name='achieved_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
