version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitbet
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: